import os
import subprocess
from Bio.PDB import MMCIFParser, PDBIO

def convert_cif_to_pdb(cif_path, pdb_path):
    try:
        parser = MMCIFParser()
        structure = parser.get_structure("cif", cif_path)
        # Check atom count
        atom_count = 0
        for _ in structure.get_atoms():
            atom_count += 1
        if atom_count > 99999:
            print(f"  Skipping {cif_path} because it has more than 99999 atoms.")
            return False

        io = PDBIO()
        io.set_structure(structure)
        io.save(pdb_path)
        print(f"  Successfully converted {cif_path} to {pdb_path}")
        return True
    except Exception as e:
        print(f"  Error converting {cif_path} to {pdb_path}: {e}")
        return False

def fix_pdb_residue_numbers(pdb_path):
    try:
        with open(pdb_path, 'r') as f:
            lines = f.readlines()
        
        with open(pdb_path, 'w') as f:
            for line in lines:
                if line.startswith("ATOM") or line.startswith("HETATM"):
                    res_seq = line[22:27].strip()
                    if not res_seq.isdigit():
                        # Attempt to fix the residue number
                        new_res_seq = "".join(filter(str.isdigit, res_seq))
                        if new_res_seq:
                            line = line[:22] + new_res_seq.rjust(4) + " " + line[27:]
                f.write(line)
        print(f"  Fixed residue numbers in {pdb_path}")
        return True
    except Exception as e:
        print(f"  Error fixing residue numbers in {pdb_path}: {e}")
        return False

PDB_FILES_DIR = "pdb_files"
PQR_FILES_DIR = "pqr_files"
APBS_OUTPUT_DIR = "apbs_results"

# Files to skip
SKIP_FILES = ["7W53.pdb", "8I0U.cif"]

os.makedirs(PQR_FILES_DIR, exist_ok=True)
os.makedirs(APBS_OUTPUT_DIR, exist_ok=True)

structure_files = [f for f in os.listdir(PDB_FILES_DIR) if (f.endswith(".pdb") or f.endswith(".cif")) and f not in SKIP_FILES]

for filename in structure_files:
    pdb_id = filename.split('.')[0]
    input_path = os.path.join(PDB_FILES_DIR, filename)
    pqr_path = os.path.join(PQR_FILES_DIR, f"{pdb_id}.pqr")

    # Run pdb2pqr
    print(f"Running PDB2PQR on {filename}...")
    pdb2pqr_command = [
        "pdb2pqr30",
        "--ff=PARSE",
        input_path,
        pqr_path
    ]
    try:
        subprocess.run(pdb2pqr_command, check=True, capture_output=True, text=True)
        print(f"  Successfully created {pqr_path}")
    except subprocess.CalledProcessError as e:
        if filename.endswith(".cif"):
            print(f"  PDB2PQR failed for {filename}. Trying to convert to PDB first.")
            pdb_path = os.path.join(PDB_FILES_DIR, f"{pdb_id}.pdb")
            if convert_cif_to_pdb(input_path, pdb_path):
                if fix_pdb_residue_numbers(pdb_path):
                    pdb2pqr_command[2] = pdb_path
                    try:
                        subprocess.run(pdb2pqr_command, check=True, capture_output=True, text=True)
                        print(f"  Successfully created {pqr_path} from converted PDB.")
                    except subprocess.CalledProcessError as e2:
                        print(f"  Error running PDB2PQR on converted {pdb_id}.pdb:")
                        print(e2.stdout)
                        print(e2.stderr)
                        continue
                else:
                    continue
            else:
                continue
        else:
            print(f"  Error running PDB2PQR on {filename}:")
            print(e.stdout)
            print(e.stderr)
            continue

    # Create APBS input file
    apbs_input_path = os.path.join(APBS_OUTPUT_DIR, f"{pdb_id}.in")
    apbs_output_prefix = os.path.join(APBS_OUTPUT_DIR, pdb_id)

    apbs_config = f"""
# APBS input file generated by script
read
    mol pqr {pqr_path}
end

elec
    mg-auto
    dime 129 129 129
    cglen 200 200 200
    fglen 100 100 100
    cgcent mol 1
    fgcent mol 1
    mol 1
    lpbe
    bcfl sdh
    pdie 2.0
    sdie 78.54
    sdens 10.0
    chgm spl2
    srfm smol
    srad 1.4
    swin 0.3
    temp 298.15
    calcenergy total
    calcforce no
    write pot dx {apbs_output_prefix}
end

quit
"""
    if pdb_id == "8T9R":
        apbs_config = apbs_config.replace("mg-auto", "mg-manual\nnlev 4")


    with open(apbs_input_path, "w") as f:
        f.write(apbs_config)

    # Run APBS
    print(f"Running APBS on {pqr_path}...")
    apbs_command = ["apbs", apbs_input_path]
    try:
        subprocess.run(apbs_command, check=True, capture_output=True, text=True)
        print(f"  Successfully ran APBS for {pdb_id}")
    except subprocess.CalledProcessError as e:
        print(f"  Error running APBS for {pdb_id}:")
        print(e.stdout)
        print(e.stderr)

print("\n\nElectrostatic analysis complete!")
